#!/bin/bash

install_config_plymouth() {
  install_packages_using_pacman "plymouth" "--needed"
  sudo sed -i -e "s/\(HOOKS.*\(systemd\)\?.*\) \(\(encrypt\|sd-encrypt\)\?\)/\1 plymouth \3/g" /etc/mkinitcpio.conf
  install_packages_using_yay "plymouth-theme-green-blocks-git" "--needed"
  sudo plymouth-set-default-theme -R green_blocks
  sudo mkinitcpio -P
}

