#!/bin/bash

### install packages using pacman

install_packages_using_pacman() {
  packages_names="$1"
  flags="$2"
  sudo pacman -S $flags $packages_names
}

### install packages using yay

install_packages_using_yay() {
  install_yay 
  packages_names="$1"
  flags="$2"
  yay -S $flags $packages_names
}

install_required_packages_yay() {
  requires_packages="git base-devel coreutils"
  install_packages_using_pacman $requires_packages "--needed"
}

# Install yay

install_yay() {
  install_required_packages_yay
  command -v yay > /dev/null
  yay_installed="$(echo $?)"
  if [[ $yay_installed -eq 1 ]]; then
    _writeLog 0 "Installing yay"
    clone_using_git "https://aur.archlinux.org/yay.git" "$config_dir"
    cd yay
    makepkg -si
    cd $config_dir
    _writeLog 0 "Installed yay"
  fi
}

# Install stow

install_stow() {
  install_packages_using_pacman "stow" "--needed"
}

# Function to make dir

makedir() {
  dir="$1"
  if [[ ! -d "$dir" ]]; then
    mkdir -p $dir
  fi
}

# Function to clone a git url

clone_using_git() {
  git_url="$1"
  clone_dir="$2"
  repo_name="$3"
  flags="$4"
  makedir "$clone_dir"
  cd "$clone_dir"
  arguments="$git_url"
  if [[ ! -z "$flags" ]]; then
    arguments="$flags $arguments"
  fi
  if [[ ! -z "$repo_name" ]]; then
    arguments="$arguments $repo_name"
  fi
  git clone $arguments
}

# Function to move dir

movedir() {
  from_dir="$1"
  to_dir="$2"
  makedir "$from_dir"
  makedir "$to_dir"
  _writeLog 0 "Moving $from_dir to $to_dir"
  mv "$from_dir" "$to_dir"
}

# Function to copy file

copyfile() {
  file_to_move="$1"
  to_dir="$2"
  makedir "$to_dir"
  if [[ -f "$file_to_move" ]]; then
    _writeLog 0 "Moving $file_to_move file to $to_dir"
    cp "$file_to_move" "$to_dir"
  fi
}

#Function to copy files

copyfiles() {
  files_dir="$1"
  to_dir="$2"
  makedir "$to_dir"
  if [[ -d "$files_dir" ]]; then
    _writeLog 0 "Moving $files_dir file to $to_dir"
    cp -r "$files_dir" "$to_dir"
  fi
}
