#!/bin/bash

### install packages using pacman

install_packages_using_pacman() {
  packages_names="$1"
  flags="$2"
  sudo pacman -S $flags $packages_names
}

### install packages using yay

install_packages_using_yay() {
  install_yay 
  packages_names="$1"
  flags="$2"
  yay -S $flags $packages_names
}

install_required_packages_yay() {
  requires_packages="git base-devel"
  install_packages $requires_packages "--needed"
}

install_yay() {
  yay_installed="$(command -v yay | echo $?)"
  if [[ $yay_installed -eq 1 ]]; then
    echo "Installing yay"
    cd $config_dir
    install_required_packages_yay
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    echo "test install"
    cd $config_dir
  fi
}

install_stow() {
  install_packages_using_pacman "stow" "--needed"
}

# install_packages_test() {
#   echo "test"
# }

