#!/bin/bash

install_required_packages() {
  required_packages="picom feh acpi rofi ttf-jetbrains-mono-nerd xorg-server xorg-apps xorg-xinit"
  install_packages_using_pacman "$required_packages" --needed
}

clone_dwm() {
  root_url="https://github.com/"
  child_url="$1"
  full_url="$root_url/$child_url"
  install_required_packages
  cd $dot_config_dir
  if [[ ! -d "chadwm/" ]]; then
    git clone $full_url
  fi
  cd $config_dir
}

install_dwm() {
  source_dir="$dot_config_dir/chadwm/chadwm"
  if [[ -d "$source_dir" ]]; then
    echo "Installing chadwm"
    cd "$source_dir"
    # sudo make install
  else
    echo "dwm install failed"
    exit -1
  fi
  cd $config_dir
}

post_install_dwm() {
  xresources_path="$dot_config_dir/chadwm/.Xresources"
  if [[ -f "$xresources_path" ]]; then
    echo "copying .Xresources to $stow_dir"
    cp "$xresources_path" "$stow_dir/.Xresources"
  fi
  eww_path="$dot_config_dir/chadwm/"
  if [[ -d "$eww_path/eww" ]]; then
    cd "$eww_path"
    echo "Moving eww to dotfiles"
    mv eww "$dot_config_dir"
  fi
  scripts_dir="$dot_config_dir/chadwm/scripts"
  if [[ -d "$scripts_dir" ]]; then
    cd $scripts_dir
    chadwm_scripts="$(find . -name '*.sh')"
    chmod +x $chadwm_scripts
  fi
  rofi_dir="$dot_config_dir/chadwm/rofi/"
  if [[ -d "$rofi_dir" ]]; then
    echo "Moving rofi to dotfiles"
    mv "$rofi_dir" "$dot_config_dir"
  fi
  xinitrc_path=$config_dir
  if [[ -d "$xinitrc_path" ]]; then
    echo "Copying Xinitrc to dotfiles"
    cp "$xinitrc_path/.xinitrc" "$stow_dir"
  fi
  wallpaper_dir="$config_dir/wallpapers"
  if [[ -d $wallpaper_dir ]]; then
    if [[ ! -d "$stow_dir/wallpapers/" ]]; then
      echo "Making directory $stow_dir/wallpapers"
      mkdir "$stow_dir/wallpapers"
    fi
    echo "Copying wallpaper to dotfiles"
    cp -r "$wallpaper_dir/" "$stow_dir/"
  fi
  cd $config_dir
}

install_config_dwm() {
  url="$1"
  clone_dwm "$url"
  install_dwm
  post_install_dwm
}
