#!/bin/bash

install_required_packages() {
  required_packages="picom feh acpi rofi ttf-jetbrains-mono-nerd xorg-server xorg-apps xorg-xinit"
  install_packages_using_pacman "$required_packages" "--needed"
}

clone_dwm() {
  root_url="https://github.com/"
  child_url="$1"
  full_url="$root_url/$child_url"
  install_required_packages
  clone_using_git "$full_url" "$dot_config_dir"
  cd $config_dir
}

install_dwm() {
  source_dir="$dot_config_dir/chadwm/chadwm"
  if [[ -d "$source_dir" ]]; then
    echo "Installing chadwm"
    cd "$source_dir"
    sudo make install
  else
    echo "dwm install failed"
    exit -1
  fi
  cd $config_dir
}

post_install_dwm() {
  xresources_dir="$dot_config_dir/chadwm/.Xresources"
  copyfile "$xresources_dir" "$stow_dir/.Xresources"

  xinitrc_file="$config_dir/.xinitrc"
  copyfile "$xinitrc_file" "$stow_dir"

  eww_dir="$dot_config_dir/chadwm/eww"
  movedir "$eww_dir" "$dot_config_dir"

  rofi_dir="$dot_config_dir/chadwm/rofi/"
  movedir "$rofi_dir" "$dot_config_dir"

  scripts_dir="$dot_config_dir/chadwm/scripts"
  if [[ -d "$scripts_dir" ]]; then
    cd $scripts_dir
    chadwm_scripts="$(find . -name '*.sh')"
    chmod +x $chadwm_scripts
  fi

  wallpaper_dir="$config_dir/wallpapers"
  if [[ -d $wallpaper_dir ]]; then
    makedir "$stow_dir/wallpapers"
    copyfiles "$wallpaper_dir" "$stow_dir"
  fi

  cd $config_dir
}

install_config_dwm() {
  url="$1"
  clone_dwm "$url"
  install_dwm
  post_install_dwm
}
