#!/bin/bash

install_config_tmux() {
  install_packages_using_pacman "tmux" "--needed"
  # git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  clone_using_git "https://github.com/tmux-plugins/tpm" "$stow_dir/.tmux/plugins/" "tpm"
}
