#! /usr/bin/env bash

initialize() {
    _writeLog 0 "Initializing"
    echo
    _writeLog 0 "Updating packages"
    sudo pacman -Syu --noconfirm 2>log
    if [[ $(echo $?) -eq 1 ]]; then
        echo
        _writeLog 2 "Failed to update packages"
        exit 1
    fi
    _writeLog 1 "Updated packages"
    echo
    if [[ ! -d $stow_dir ]]; then
        _writeLog 0 "Creating stow directory $stow_dir"
        mkdir -p $stow_dir
    fi
    if [[ ! -d "$dot_config_dir" ]]; then
        _writeLog 0 "Creating dot-config directory in $stow_dir"
        mkdir "$dot_config_dir"
    fi
    install_yay
    _writeLog 1 "Initialization Success"
}
