#!/bin/bash

# install packages using pacman
install_packages_using_pacman() {
    packages_names="$1"
    flags="$2"
    sudo pacman -S --noconfirm $flags $packages_names
}

# install packages using yay
install_packages_using_yay() {
    install_yay 
    packages_names="$1"
    flags="$2"
    yay -S --noconfirm $flags $packages_names
}

# install packages required for yay
install_required_packages_yay() {
    requires_packages="git base-devel coreutils"
    install_packages_using_pacman "$requires_packages" "--needed"
}

# Install yay
install_yay() {
    install_required_packages_yay
    command -v yay > /dev/null
    yay_installed="$(echo $?)"
    if [[ $yay_installed -eq 1 ]]; then
        _writeLog 0 "Installing yay"
        clone_using_git "https://aur.archlinux.org/yay.git" "$config_dir"
        cd yay
        makepkg -si
        cd $config_dir
        _writeLog 1 "Installed yay"
        echo
    else
        _writeLog 0 "Yay already installed"
        echo
    fi
}

